blank_issues_enabled: false
contact_links:
  - name: View documentation
    url: https://next-intl.dev/
    about: Check out the official docs for answers to common questions
  - name: Get community support
    url: https://stackoverflow.com/questions/ask
    about: Ask questions and discuss with other community members
  - name: Get maintainer support
    url: https://github.com/sponsors/amannn?frequency=one-time
    about: Book a consulting session to get help with your specific project
